### ISSUE TITLE
How to integrate it

### ISSUE THREAD

**Issue by naveenavemuri** [luizbills/stats.js.hx#1]
HI 

   I have placed the haxelib.json file in the project and added the <script type="text/javascript" src="./src/pixi/plugins/stats/Stats.hx"></script>   and  <script src="./build/stats.min.js"></script> in my index.html
but still i was unable to view fps in the ui layer. i am missing any thing .plz help me

**Comment by luizbills** [comment]
use `haxelib` to install.
